server {
    listen 443 ssl;
    server_name zalaksya.42.fr;
    ssl_certificate /etc/nginx/zalaksya.crt;
    ssl_certificate_key /etc/nginx/zalaksya.key;
    ssl_protocols TLSv1.3;
    location / {
        root /var/www/html;
        index index.html;
    }
}
