services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
  mariadb:
    build: requirements/mariadb
    networks:
      - inception

networks:
  inception:

volumes:
  wordpress: