services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql

networks:
  inception:
    name: inception

volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/