services:
  nginx:
    build: requirements/nginx
    ports: 
      - "443:443"
    networks:
      - inception
  wordpress:

    build: requirements/wordpress
    networks:
      - inception
  mriadb:
    build: requirements/mariadb
    networks:
      - inception
networks:
  inception: